spring:
  application:
    name: EXCEL
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/file_management
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none